package asunit.framework.support {

	public class ErrorInMethodTest {
		
		public function test_throw_ArgumentError():void {
			throw new ArgumentError('generated by ErrorInMethodTest');
		}
		
	}
}
